[package]
name = "tok-pdf"
version.workspace = true
edition.workspace = true
authors.workspace = true
license-file.workspace = true

[dependencies]
tok-core = { workspace = true }
tok-typeset = { workspace = true }
pdf-writer = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
log = { workspace = true }
subsetter = "0.2"
ttf-parser = "0.24"
